# Generated by Django 3.2.5 on 2022-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='name',
            field=models.CharField(default='Liste', max_length=100),
        ),
    ]
