# Generated by Django 3.2.5 on 2022-12-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0002_wordlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=60)),
                ('duration', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('word_count', models.IntegerField()),
                ('correct_count', models.IntegerField()),
            ],
        ),
    ]
