# Generated by Django 3.2.5 on 2023-01-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shuffled_words',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
