# Generated by Django 3.2.5 on 2023-03-03 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordlists', '0006_usertests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTests',
            new_name='UserWordlists',
        ),
    ]
