# Generated by Django 3.2.5 on 2023-04-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0009_auto_20230406_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordlists.patient'),
        ),
    ]
