# Generated by Django 3.2.5 on 2023-04-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0010_alter_test_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='participant',
        ),
        migrations.AddField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wordlists.patient'),
            preserve_default=False,
        ),
    ]
