# Generated by Django 3.2.5 on 2023-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlists', '0012_patient_anzeige (in ms)'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='duration_time',
            field=models.IntegerField(default=1000, verbose_name='Anzeige (in ms)'),
        ),
    ]
